build:
    verbosity: detailed
install:
    ############################################################################
    # All external dependencies are installed in C:\projects\deps
    ############################################################################
    - mkdir C:\projects\deps
    - cd C:\projects\deps

    ############################################################################
    # Install Ninja
    ############################################################################
    - set URHO3D_URL="https://downloads.sourceforge.net/project/urho3d/Urho3D/1.6/Urho3D-1.6-Windows-64bit-STATIC.zip?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Furho3d%2Ffiles%2FUrho3D%2F1.6%2F&ts=1511708773&use_mirror=iweb"
    - appveyor DownloadFile %URHO3D_URL% -FileName urho3d.zip
    - 7z x urho3d.zip -oC:\projects\deps\Urho3D > nul
before_build:
    - cd C:\projects\prograde
build_script:
    - cd C:\projects\deps\Urho3D
    - dir
    #    - mkdir build
    #    - cd build
    #    - cmake .. -DBOOST_ROOT="C:\Libraries\boost"
    #    - cmake --build . --target prograde
    #    - cmake --build . --target prograde_test
