build:
    verbosity: detailed
install:
    ############################################################################
    # All external dependencies are installed in C:\projects\deps
    ############################################################################
    - mkdir C:\projects\deps
    - cd C:\projects\deps

    ############################################################################
      # Install GSL
    ############################################################################
    - set GSL_URL="https://netix.dl.sourceforge.net/project/gnu-scientific-library-windows/gsl-2.2.1_mingw-6.2.0.zip"
    - call curl.exe -sS -o gsl.zip %GSL_URL%
    - 7z x gsl.zip -oC:\projects\deps\gsl > nul
    - set PATH=C:\projects\deps\gsl\gsl-2.2.1_mingw-6.2.0\gsl-2.2.1-shared;%PATH%
    - cd C:\projects\deps\gsl\gsl-2.2.1_mingw-6.2.0\gsl-2.2.1-shared
    - dir
    - cd C:\projects\deps
before_build:
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
    - cd C:\projects\prograde
build_script:
    - mkdir build
    - cd build
    - cmake .. -DBOOST_ROOT="C:\Libraries\boost"
    - cmake --build . --target prograde
    - cmake --build . --target prograde_test
