build:
    verbosity: detailed
build_script:
    - git clone https://github.com/Urho3D/Urho3D.git
    - cd Urho3D/
    - mkdir build
    - cmake_vs2015.bat build/
    - cd build/
    - dir
    #    - mkdir build
    #    - cd build
    #    - cmake .. -DBOOST_ROOT="C:\Libraries\boost"
    #    - cmake --build . --target prograde
    #    - cmake --build . --target prograde_test
