build:
    verbosity: detailed
build_script:
    - mkdir build
    - cd build
    - cmake .. -DBOOST_ROOT="C:\Libraries\boost"
    - cmake --build . --target prograde
    - cmake --build . --target prograde_test
