build:
    verbosity: detailed
install:
    ############################################################################
    # All external dependencies are installed in C:\projects\deps
    ############################################################################
    - mkdir C:\projects\deps
    - cd C:\projects\deps

    ############################################################################
    # Install Ninja
    ############################################################################
    - set URHO3D_URL="https://downloads.sourceforge.net/project/urho3d/Urho3D/1.6/Urho3D-1.6-Windows-64bit-STATIC.zip?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Furho3d%2Ffiles%2FUrho3D%2F1.6%2F&ts=1511708773&use_mirror=iweb"
      #- appveyor DownloadFile %URHO3D_URL% -FileName urho3d.zip
      #- 7z x urho3d.zip -oC:\projects\deps\Urho3D > nul
    - set URHO3D_LIBRARIES="C:/projects/deps/Urho3D/Urho3D-1.6-Windows-64bit-STATIC/lib64/Urho3D/libUrho3D.a"
    - set URHO3D_INCLUDE_DIR="C:\projects\deps\Urho3D\Urho3D-1.6-Windows-64bit-STATIC\include;C:\projects\deps\Urho3D\Urho3D-1.6-Windows-64bit-STATIC\include\Urho3D\ThirdParty"

    # CMake refuses to generate MinGW Makefiles if sh.exe is in the Path
    - ps: Get-Command sh.exe -All | Remove-Item
before_build:
    - set Path=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin;%Path%
    - cd C:\projects\prograde
build_script:
    - mkdir build
    - cd build
    - cmake .. -G "MinGW Makefiles" -DBOOST_ROOT="C:\Libraries\boost" -DCMAKE_SH="CMAKE_SH-NOTFOUND" #-DURHO3D_LIBRARIES=%URHO3D_LIBRARIES% -DURHO3D_INCLUDE_DIR=%URHO3D_INCLUDE_DIR%
    - cmake --build . --target prograde
    - cmake --build . --target prograde_test
