language: cpp
compiler:
    - gcc
    - clang
addons:
    apt:
        packages:
            - libboost1.55-dev
            - clang-3.8
            - clang-format-3.8
            - clang-tidy-3.8
            - doxygen

script:
    - mkdir build
    - cd build/
    - cmake ..
    - make -j 4 prograde prograde_test
    - ./prograde_test
    - make clang-format
    - make clang-tidy
    - make doc
    - mkdir prograde-$TRAVIS_OS_NAME-x86-64-$CXX/
    - mv prograde prograde-$TRAVIS_OS_NAME-x86-64-$CXX/
    - mv ../data prograde-$TRAVIS_OS_NAME-x86-64-$CXX/
    - tar -zcvf prograde-$TRAVIS_TAG-$TRAVIS_OS_NAME-x86-64-$CXX.tar.gz prograde-$TRAVIS_OS_NAME-x86-64-$CXX/


deploy:
    - provider: pages
      local_dir: html/
      skip_cleanup: true
      github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
      on:
          branch: master

    - provider: releases
      api_key:
          secure: H76B2KEpl4ala+UMH67cDhatahlzhjRW0Z0R1chkOoKKxIuPmBjAN1S+xdHc28g9x+b1IEpe79g12hj/DA+89fLhToxea+LAC0wOcDe2FhyL1j2aLKnUNm+8kHjeOuFVwAPkizdwVIpcwrk1fOruftyh+d6Jh2ldCG5fBKmHoNv4StRMq9u3xpoRd6EiBf8p3PFr17o/KyWRKYpCw4LQ676uycJXgwz0JXUkGPkFl2hTv1mO0/zc25kuKNuPLHX0oxfLN95FsxH2tpHcUdzKBXCQv1Y4c9DbQbmsb2mDZoINnANUG/Ma6xK7ati8ZeiAqD1eCflVGxpWaJPfIwEk992P/sRJzgcBHT1GChCG00CJ8psOsWgUWwxk4TcrzABF/rmM04hd+cxWow77UjeQLhSQAqw9a9MlBPqNzg/J+C1+O8x98kfmu7LIW/kIzi9IGIcWWpajlhKrPfyVQPh7piI6eSvAMfwGda1jQnM6+ZFto3CH5fMBkyTFK+YwV1G+Y/XQHIo2M0onRfdOiS2dhnpllv9KKTgjtJin+pb5kRjrLx6iDMCn6r32BMSp2FFR3V3/w0gWrpkx7ooixWwkb1KzQHZrU1DL3kU7HTj6tGORnRTRWolilt6JiUs06FzrZa7p0qTJmusZqaUF3LS/TigS881zrfbY0A2mv7v6DAA=
      file: "prograde-$TRAVIS_TAG-$TRAVIS_OS_NAME-x86-64-$CXX.tar.gz"
      skip_cleanup: true
      on:
          tags: true
