var annotated =
[
    [ "constant", "namespaceconstant.html", null ],
    [ "Camera", "classCamera.html", "classCamera" ],
    [ "CelestialBody", "classCelestialBody.html", "classCelestialBody" ],
    [ "CelestialBodyDrawer", "classCelestialBodyDrawer.html", "classCelestialBodyDrawer" ],
    [ "Color", "classColor.html", "classColor" ],
    [ "CoordinateSystem", "classCoordinateSystem.html", "classCoordinateSystem" ],
    [ "CriticalException", "classCriticalException.html", "classCriticalException" ],
    [ "Drawer", "classDrawer.html", "classDrawer" ],
    [ "EccentricAnomalySolver", "classEccentricAnomalySolver.html", "classEccentricAnomalySolver" ],
    [ "Exceptions", "classExceptions.html", "classExceptions" ],
    [ "Gui", "classGui.html", "classGui" ],
    [ "KerbalSystem", "classKerbalSystem.html", "classKerbalSystem" ],
    [ "LauncherWindow", "classLauncherWindow.html", "classLauncherWindow" ],
    [ "MainWindow", "classMainWindow.html", "classMainWindow" ],
    [ "Matrix4x4", "classMatrix4x4.html", "classMatrix4x4" ],
    [ "Orbit", "classOrbit.html", "classOrbit" ],
    [ "OrbitalSystem", "classOrbitalSystem.html", "classOrbitalSystem" ],
    [ "OrbitalSystemDrawer", "classOrbitalSystemDrawer.html", "classOrbitalSystemDrawer" ],
    [ "SimulationTime", "classSimulationTime.html", "classSimulationTime" ],
    [ "SkyboxGenerator", "classSkyboxGenerator.html", "classSkyboxGenerator" ],
    [ "SolarSystem", "classSolarSystem.html", "classSolarSystem" ],
    [ "Vector3", "classVector3.html", "classVector3" ],
    [ "Vector4", "classVector4.html", "classVector4" ]
];